service: apollo-lambda

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  graphql:
    handler: ./src/index.handler
    events:
      - http:
          path: /
          method: post
          cors: true

custom:
  serverless-offline:
    noPrependStageInUrl: true
    useChildProcesses: true
    host: 0.0.0.0
    httpPort: 8083
    websocketPort: 4083
    lambdaPort: 5083
